apiVersion: skaffold/v1beta1
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/dmathew-pendosystems/spring-boot-rest-prometheus:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/dmathew-pendosystems/spring-boot-rest-prometheus:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: spring-boot-rest-prometheus
        chartPath: charts/spring-boot-rest-prometheus
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/dmathew-pendosystems/spring-boot-rest-prometheus'
          image.tag: '{{.DIGEST_HEX}}'
